; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino
board_build.flash_mode = dout
board_build.f_cpu = 80000000L
upload_protocol = esptool
upload_port = /dev/cu.usbserial-210
upload_speed = 115200
board_build.ldscript = eagle.flash.4m1m.ld
lib_deps = 
	bodmer/TJpg_Decoder@^1.1.0
	paulstoffregen/Time@^1.6.1
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.21.5
	bodmer/TFT_eSPI@^2.5.43
lib_ignore = 
	SD
	SDFS
	ESP8266SdFat
build_flags = 
	-DFACTORY_CONFIG_H
    ; 优化：-Os 减小固件体积（ESP8266 flash 有限）
    -Os
    ; 下面两行在编译时自动把 User_Setup.h 注入到 TFT_eSPI
    ; 这样就不用手动去改库目录下的文件了
    -include $PROJECT_DIR/User_Setup.h
    -DUSER_SETUP_LOADED=1
