; PlatformIO Project Configuration File

; ===================== 公共基础 =====================
[common]
platform = espressif8266
board = nodemcu
framework = arduino
board_build.flash_mode = dout
board_build.f_cpu = 80000000L
upload_protocol = esptool
upload_speed = 115200
board_build.ldscript = eagle.flash.4m1m.ld

; ===================== 接收端 =====================
[env:nodemcu_receiver]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
board_build.flash_mode = ${common.board_build.flash_mode}
board_build.f_cpu = ${common.board_build.f_cpu}
upload_protocol = ${common.upload_protocol}
upload_port = /dev/cu.usbserial-1130
upload_speed = ${common.upload_speed}
board_build.ldscript = ${common.board_build.ldscript}
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
build_flags = 
	-Os
	-include $PROJECT_DIR/User_Setup.h
	-DUSER_SETUP_LOADED=1
	-DESPNOW_MODE_RECEIVER

; ===================== 基站 =====================
[env:nodemcu_sender]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
board_build.flash_mode = ${common.board_build.flash_mode}
board_build.f_cpu = ${common.board_build.f_cpu}
upload_protocol = ${common.upload_protocol}
upload_port = /dev/cu.usbserial-1140
upload_speed = ${common.upload_speed}
board_build.ldscript = ${common.board_build.ldscript}
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
build_flags = 
	-Os
	-include $PROJECT_DIR/User_Setup.h
	-DUSER_SETUP_LOADED=1
	-DESPNOW_MODE_SENDER

; 排除接收端源码
src_filter = +<*> -<espnow_receiver.cpp>
