; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif8266
board = nodemcu
framework = arduino
board_build.flash_mode = dout
board_build.f_cpu = 80000000L
upload_protocol = esptool
upload_speed = 115200
board_build.ldscript = eagle.flash.4m1m.ld

[env:nodemcu_receiver]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
board_build.flash_mode = ${common.board_build.flash_mode}
board_build.f_cpu = ${common.board_build.f_cpu}
upload_protocol = ${common.upload_protocol}
upload_port = /dev/cu.usbserial-1130
upload_speed = ${common.upload_speed}
board_build.ldscript = ${common.board_build.ldscript}
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	bodmer/TJpg_Decoder@^1.1.0
build_flags = 
	-Os
	-include $PROJECT_DIR/User_Setup.h
	-DUSER_SETUP_LOADED=1
	-DESPNOW_MODE_RECEIVER
	-DSERIAL_RX_BUFFER_SIZE=4096

[env:nodemcu_sender]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
board_build.flash_mode = ${common.board_build.flash_mode}
board_build.f_cpu = ${common.board_build.f_cpu}
upload_protocol = ${common.upload_protocol}
upload_port = /dev/cu.usbserial-1140
upload_speed = ${common.upload_speed}
board_build.ldscript = ${common.board_build.ldscript}
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	bodmer/TJpg_Decoder@^1.1.0
build_flags = 
	-Os
	-include $PROJECT_DIR/User_Setup.h
	-DUSER_SETUP_LOADED=1
	-DESPNOW_MODE_SENDER
	-DSERIAL_RX_BUFFER_SIZE=4096
src_filter = +<*> -<espnow_receiver.cpp>

[env:nodemcu_sender_selftest]
platform = ${env:nodemcu_sender.platform}
board = ${env:nodemcu_sender.board}
framework = ${env:nodemcu_sender.framework}
board_build.flash_mode = ${env:nodemcu_sender.board_build.flash_mode}
board_build.f_cpu = ${env:nodemcu_sender.board_build.f_cpu}
upload_protocol = ${env:nodemcu_sender.upload_protocol}
upload_port = ${env:nodemcu_sender.upload_port}
upload_speed = ${env:nodemcu_sender.upload_speed}
board_build.ldscript = ${env:nodemcu_sender.board_build.ldscript}
lib_deps = 
	${env:nodemcu_sender.lib_deps}
	bodmer/TJpg_Decoder@^1.1.0
build_flags = 
	${env:nodemcu_sender.build_flags}
	-DESPNOW_SELF_TEST
src_filter = ${env:nodemcu_sender.src_filter}
